[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
atty = "0.2"
cfg-if = "0.1"
duct = "0.13"
err-derive = "0.2.1"
futures01 = { package = "futures", version = "0.1" }
futures = { package = "futures", version = "0.3", features = [ "compat" ]}
hex = "0.4"
ipnetwork = "0.16"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde"] }
os_pipe = "0.8"
parking_lot = "0.9"
regex = "1.1.0"
shell-escape = "0.1"
talpid-types = { path = "../talpid-types" }
tokio-core = "0.1"
tokio-executor = "0.1"
uuid = { version = "0.7", features = ["v4"] }
zeroize = "1"
chrono = "0.4"
parity-tokio-ipc = "0.7"
tokio02 = { package = "tokio", version = "0.2", features =  [ "io-util", "process", "rt-core", "rt-threaded", "stream"] }
triggered = "0.1.1"
tonic = "0.2"
prost = "0.6"
rand = "0.7"


[target.'cfg(unix)'.dependencies]
nix = "0.17"
tokio-io = "0.1"


[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.2.3", features = ["derive"] }


[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.6"
failure = "0.1"
notify = "4.0"
resolv-conf = "0.6.1"
async-stream = "0.2"
rtnetlink = "0.2"
netlink-packet-route = "0.2"
netlink-proto = "0.2"
netlink-sys = "0.2"
futures = { package = "futures", version = "0.3" }
nftnl = { version = "0.5", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2.0", features = ["mnl-1-0-4"] }
which = { version = "3.1", default-features = false }
tun = "0.4.3"


[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.4"
system-configuration = "0.4"
tun = "0.4.3"


[target.'cfg(windows)'.dependencies]
widestring = "0.4"
winreg = "0.6"
winapi = { version = "0.3.6", features = ["handleapi", "ifdef", "libloaderapi", "netioapi", "synchapi", "winbase", "winuser"] }
socket2 = "0.3"
pnet_packet = "0.22"

[build-dependencies]
tonic-build = { version = "0.2", default-features = false, features = ["transport", "prost"] }


[dev-dependencies]
tempfile = "3.0"
quickcheck = "0.9"
quickcheck_macros = "0.9"
